'use client'

import { useEffect, useState } from 'react'
import { Activity, ArrowUpRight, Bot, Check, ChevronRight, CircleAlert, Cloud, Copy, ExternalLink, Gauge, LockKeyhole, Pause, Play, Radio, RefreshCw, ShieldCheck, Siren, Zap } from 'lucide-react'

type Event = { t: string; kind: string; amount?: number | string; regime?: string; note: string; sig?: string }
type State = { regime: string; multiplierPct: number | string; oracleRegime: string; oracleAgeSecs: number | null; oracleStale: boolean; paused: boolean; spent: number | string; limitToday: number | string; remaining: number | string; baseLimit: number | string; usedPct: number; demoCrash: boolean; events: Event[]; addresses: { program: string; oracle: string; policy: string; agent: string } }

const explorer = (kind: string, value: string) => `https://explorer.solana.com/${kind}/${value}?cluster=devnet`
const initialState: State = { regime: 'CALM', multiplierPct: 100, oracleRegime: 'CALM', oracleAgeSecs: null, oracleStale: false, paused: false, spent: '—', limitToday: '—', remaining: '—', baseLimit: '—', usedPct: 0, demoCrash: false, events: [], addresses: { program: '', oracle: '', policy: '', agent: '' } }

function StatusPill({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'neutral' | 'green' | 'amber' | 'red' }) { return <span className={`status-pill ${tone}`}><span className="status-dot" />{children}</span> }
function SectionTitle({ icon: Icon, title, action }: { icon: React.ElementType; title: string; action?: React.ReactNode }) { return <div className="section-title"><div className="section-label"><Icon size={15} />{title}</div>{action}</div> }

export default function Page() {
  const [state, setState] = useState<State>(initialState)
  const [online, setOnline] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState('')

  async function poll() { try { const response = await fetch('/api/state'); const json = await response.json(); if (!response.ok) throw new Error(json.error || response.status); setState(json); setOnline(true); setError('') } catch (e) { setOnline(false); setError(`Could not read state: ${(e as Error).message}`) } }
  async function post(path: string, body: object) { try { const response = await fetch(path, { method: 'POST', headers: { 'content-type': 'application/json', 'x-regimeguard': '1' }, body: JSON.stringify(body) }); const json = await response.json(); if (!response.ok) throw new Error(json.error || response.status); await poll() } catch (e) { setError(`Action failed: ${(e as Error).message}`) } }
  useEffect(() => { poll(); const interval = setInterval(poll, 4000); return () => clearInterval(interval) }, [])
  const regime = state.regime.toLowerCase()
  const age = state.oracleAgeSecs === null ? 'Never' : state.oracleAgeSecs < 90 ? `${state.oracleAgeSecs}s ago` : `${Math.round(state.oracleAgeSecs / 60)}m ago`
  const copyAddress = async (key: string, value: string) => { if (!value) return; await navigator.clipboard.writeText(value); setCopied(key); setTimeout(() => setCopied(''), 1500) }

  return <main className="app-shell">
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <div className="dashboard">
      <header className="topbar">
        <div className="brand"><div className="brand-mark"><ShieldCheck size={20} /></div><div><div className="brand-name">Regime<span>Guard</span></div><div className="brand-sub">Autonomous risk controls</div></div></div>
        <div className="top-actions"><StatusPill tone={online ? 'green' : 'red'}>{online ? 'System operational' : 'Connection offline'}</StatusPill><span className="network-pill"><span className="network-dot" />SOLANA DEVNET</span><button className="icon-button" onClick={poll} aria-label="Refresh state"><RefreshCw size={16} /></button></div>
      </header>
      {error && <div className="error-banner"><CircleAlert size={16} />{error}</div>}
      <section className="hero"><div><div className="eyebrow"><Radio size={14} />LIVE RISK MONITORING <span>·</span> UPDATED EVERY 4 SEC</div><h1>Guard your agent<br /><em>before the market does.</em></h1><p>RegimeGuard automatically adjusts your agent&apos;s spending authority as market conditions change — enforced on-chain, without a central point of failure.</p></div><div className="hero-meta"><div className="hero-meta-line"><span>Policy engine</span><strong><span className="tiny-dot" />Active</strong></div><div className="hero-meta-line"><span>Last oracle update</span><strong>{age}</strong></div><div className="hero-meta-line"><span>Enforcement</span><strong><LockKeyhole size={13} />On-chain</strong></div></div></section>
      <section className="metric-grid">
        <article className={`panel regime-panel ${regime}`}><SectionTitle icon={Activity} title="Current regime" action={<span className="live-label"><span className="pulse" />LIVE</span>} /><div className="regime-content"><div><div className="regime-value">{state.regime}</div><div className="regime-caption">Market conditions are {regime === 'calm' ? 'stable' : 'requiring caution'}.</div></div><div className="regime-icon"><Gauge size={32} /></div></div><div className="divider" /><div className="stat-row"><div><span>Limit multiplier</span><strong>{state.multiplierPct}% <small>of base</small></strong></div><div><span>Oracle reading</span><strong>{state.oracleRegime}</strong></div><div><span>Oracle freshness</span><strong className={state.oracleStale ? 'bad-text' : 'good-text'}>{state.oracleStale ? 'Stale' : 'Fresh'}</strong></div></div></article>
        <article className="panel budget-panel"><SectionTitle icon={Gauge} title="Today&apos;s spending budget" action={<span className="date-label">OCT 09, 2026</span>} /><div className="budget-numbers"><div><span className="number-main">{state.spent}</span><span className="number-label"> spent</span></div><div className="budget-limit"><span>of</span><strong>{state.limitToday}</strong><span>tokens</span></div></div><div className="progress-track"><div className="progress-fill" style={{ width: `${Math.min(state.usedPct, 100)}%` }} /></div><div className="budget-footer"><span><b>{state.remaining}</b> remaining today</span><span>{state.usedPct}% utilized</span></div><div className="base-limit">Base daily limit <strong>{state.baseLimit} tokens</strong></div></article>
      </section>
      <section className="lower-grid"><article className="panel controls-panel"><SectionTitle icon={Zap} title="Operator controls" action={<StatusPill tone="green">Owner only</StatusPill>} /><p className="panel-description">Emergency controls for the autonomous spending policy. Changes take effect on-chain.</p><div className="control-list"><button className={`control-button ${state.paused ? 'resume' : ''}`} onClick={() => post('/api/pause', { paused: !state.paused })}>{state.paused ? <Play size={16} /> : <Pause size={16} />}<span><strong>{state.paused ? 'Resume agent' : 'Pause agent'}</strong><small>{state.paused ? 'Restore normal operation' : 'Stop all agent activity'}</small></span><ChevronRight size={16} /></button><button className={`control-button danger ${state.demoCrash ? 'active' : ''}`} onClick={() => post('/api/demo-crash', { on: !state.demoCrash })}><Siren size={16} /><span><strong>{state.demoCrash ? 'Stop crash simulation' : 'Simulate market crash'}</strong><small>{state.demoCrash ? 'Return to normal conditions' : 'Test crisis enforcement'}</small></span><ChevronRight size={16} /></button></div><div className="control-note"><CircleAlert size={14} />Simulation only appends a synthetic price drop. No real market data is changed.</div></article>
        <article className="panel addresses-panel"><SectionTitle icon={LockKeyhole} title="On-chain addresses" action={<a href="https://explorer.solana.com/?cluster=devnet" target="_blank" rel="noreferrer" className="external-link">Explorer <ExternalLink size={12} /></a>} /><div className="address-list">{Object.entries(state.addresses).map(([key, value]) => <div className="address-row" key={key}><span>{key === 'program' ? 'Guard program' : key === 'oracle' ? 'Oracle account' : key === 'policy' ? 'Policy account' : 'Agent wallet'}</span><div><a href={value ? explorer('address', value) : '#'} target="_blank" rel="noreferrer">{value || 'Waiting for state…'}</a>{value && <button onClick={() => copyAddress(key, value)} aria-label={`Copy ${key} address`}>{copied === key ? <Check size={13} /> : <Copy size={13} />}</button>}</div></div>)}</div></article></section>
      <article className="panel activity-panel"><SectionTitle icon={Bot} title="Agent activity" action={<span className="activity-count">{state.events.length} events</span>} /><div className="table-wrap"><table><thead><tr><th>TIME</th><th>EVENT</th><th>AMOUNT</th><th>REGIME</th><th>DETAIL</th></tr></thead><tbody>{state.events.length ? state.events.map((event, index) => <tr key={`${event.t}-${index}`}><td className="time-cell">{new Date(event.t).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</td><td><span className={`event-badge ${event.kind.toLowerCase()}`}>{event.kind}</span></td><td>{event.amount ?? '—'}</td><td><span className={`regime-mini ${event.regime?.toLowerCase()}`}>{event.regime ?? '—'}</span></td><td>{event.note} {event.sig && <a href={explorer('tx', event.sig)} target="_blank" rel="noreferrer" className="tx-link">View tx <ArrowUpRight size={12} /></a>}</td></tr>) : <tr><td colSpan={5} className="empty-state"><Bot size={18} />No activity yet. Start the agent with <code>npm run agent</code></td></tr>}</tbody></table></div><div className="legend"><span><i className="legend-dot buy" />BUY allowed</span><span><i className="legend-dot wait" />WAIT self-paused</span><span><i className="legend-dot rejected" />REJECTED by chain</span></div></article>
      <footer><span>REGIMEGUARD <b>v1.0.0</b></span><span>Risk controls for autonomous agents <span className="footer-dot" /> Built on Solana</span></footer>
    </div>
  </main>
}
